services:
  - type: web
    name: strapi
    env: node
<<<<<<< HEAD
    plan: starter
=======
    plan: free
>>>>>>> dd1810de7013aea3d9549188fbf40cf41d76c51f
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: strapi
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true

databases:
  - name: strapi
<<<<<<< HEAD
    plan: starter
=======
    plan: free
>>>>>>> dd1810de7013aea3d9549188fbf40cf41d76c51f
